YaMehdiData/urls.py
from django.contrib import admin
from django.urls import include, path
# this is to use URL i/o of PATH in 'urlpatterns = []'
from django.conf.urls import url 
#from serverAPI import views
from serverAPI.api import *

urlpatterns = [
    path('admin/', admin.site.urls),    #route to ADMIN Page only
    
    path('', include('mainpage.urls')), #route to Main Login Page only
    # path to Create Server APIs
    path('sammar_rest_api/', include('haq.urls')), #route to Haq App but won't display any page

    # path to serverAPI
    path('rest_api/authPerson_list/', AuthPersonList.as_view(), name='authPerson_list'),
    path('rest_api/topics_list/', TopicList.as_view(), name='topics_list'),
    path('rest_api/categories_list/', CategoryList.as_view(), name='topics_list'),
    path('rest_api/statuss_list/', StatusList.as_view(), name='topics_list'),
    path('rest_api/religions_list/', ReligionList.as_view(), name='topics_list'),
    path('rest_api/persons_list/', PersonList.as_view(), name='topics_list'),
    path('rest_api/needs_list/', NeedList.as_view(), name='topics_list'),
    path('rest_api/languages_list/', LanguageList.as_view(), name='topics_list'),
    path('rest_api/books_list/', BookList.as_view(), name='topics_list'),
    path('rest_api/references_list/', ReferenceList.as_view(), name='topics_list'),

]

haq/urls.py
from django.urls import path, include
from django.conf.urls import url

from . import views

app_name = "haq"
               
urlpatterns = [
    path('logout', views.LogOutView, name="logout"),
    # JSON Files routes
    path('', views.CreateJSONView, name="createJSON"),
    path('postJSON', views.PostJSONView, name="postJSON"),
    path('addNeed', views.AddNeedView, name="addName"),
    path('deleteNeed', views.DeleteNeedView, name="addName"),

    #  other ways to write route
    # path('getTopic/', views.GetTopicView, name="getTopic"),
    # url(r'^getPersonRef/(?P<person_id>[0-9]+)/$', views.GetPersonRefView, name="getPersonRef"),
    # url(r'^getTopic/(?P<topic_id>[0-9]+)/$', views.GetTopicView, name="getTopic"),
    # url(r'^getCategoriesBooks/(?P<category_id>[0-9]+)/$', views.GetCategoriesBooksView, name="getCategoriesBooks"),
    # path(r'^getCategoriesBooks/(?P<category_id>\d+)/$', views.GetCategoriesBooksView, name="getCategoriesBooks"),
    # url(r'^getStatusBooks/(?P<status_id>[0-9]+)/$', views.GetStatusBooksView, name="getStatusBooks"),
    # url(r'^getReligiousBooks/(?P<sect_id>[0-9]+)/$', views.GetReligiousBooksView, name="getReligiousBooks"),
    # url(r'^getNeedBooks/(?P<need_id>[0-9]+)/$', views.GetNeedBooksView, name="getNeedBooks"),
    # url(r'getLanguagesBooks/(?P<language_id>[0-9]+)/$', views.GetLanguagesBooksView, name="getLanguagesBooks"),
    # url(r'^getTopic/(?P<topic_id>\d+)/', views.GetTopicView, name="getTopic"),
    # path(r'getPersonRef/<int:person_id>/', views.GetPersonRefView, name="getPersonRef"),
]

haq/models.py
from django.db import models
from django.db.models.deletion import CASCADE

# Create your models here.
## Words Dictionary - CRUD
# 'P' => Permanent Data
# 'N' => Post, New Entry
# 'U' => Update, Updated Entry
# 'D' => Delete, Deleted Entry

    # Authorized Persons
class Authorized_Person(models.Model):
    auth_name = models.CharField(max_length=10)
    data_status = models.CharField(max_length=1, default='P')
    data_user = models.CharField(max_length=10, default='Admin')

    def __str__(self):
        return self.auth_name

 # research Topics
class Topic(models.Model):
    _topic = models.CharField(max_length=50)
    data_status = models.CharField(max_length=1, default='P')
    data_user = models.CharField(max_length=10, default='Admin')

    def __str__(self):
        return self._topic

# Person either a reportor, writer or well known personality
class Person(models.Model):
    _p_name = models.CharField(max_length = 40)
    _birth_year = models.CharField(max_length=4)
    _death_year = models.CharField(max_length=4)
    data_status = models.CharField(max_length=1, default='P')
    data_user = models.CharField(max_length=10, default='Admin')

    def __str__(self):
        return self._p_name


# Category models here.
class Category(models.Model):
    _category = models.CharField(max_length=22)
    data_status = models.CharField(max_length=1, default='P')
    data_user = models.CharField(max_length=10, default='Admin')

    def __str__(self):
        return self._category

# Language models here.
class Language(models.Model):
    _language = models.CharField(max_length=7)
    data_status = models.CharField(max_length=1, default='P')
    data_user = models.CharField(max_length=10, default='Admin')

    def __str__(self):
        return self._language

# Need models here.
class Need(models.Model):
    _need = models.CharField(max_length=9)
    data_status = models.CharField(max_length=3, default='-P-')
    data_user = models.CharField(max_length=10, default='Admin')

    def __str__(self):
        return self._need


# Religion / Sect models here.
class Religion(models.Model):
    _sect = models.CharField(max_length=20)
    data_status = models.CharField(max_length=3, default='-P-')
    data_user = models.CharField(max_length=10, default='Admin')

    def __str__(self):
        return self._sect


# Status models here.
class Status(models.Model):
    _status = models.CharField(max_length=16)
    data_status = models.CharField(max_length=3, default='-P-')
    data_user = models.CharField(max_length=10, default='Admin')

    def __str__(self):
        return self._status


# Book models here.
class Book(models.Model):
    name = models.CharField(max_length=50)
    author = models.ForeignKey(Person, on_delete=models.CASCADE)
    sect = models.ForeignKey(Religion, on_delete=models.CASCADE)
    cat = models.ForeignKey(Category, on_delete=models.CASCADE)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    need = models.ForeignKey(Need, on_delete=models.CASCADE)
    lang = models.ForeignKey(Language, on_delete=models.CASCADE)
    data_status = models.CharField(max_length=3, default='-P-')
    data_user = models.CharField(max_length=10, default='Admin')

    def __str__(self):
        return self.name.capitalize() + ' sect: ' + str(self.sect) + ' & language: ' + str(self.lang)

#####################################
########### IMPROVE ABOVE #############
#####################################
# Reference Model
class Reference(models.Model):
    subject = models.ForeignKey(Topic, on_delete=models.CASCADE)
    speaker = models.ForeignKey(Person, related_name="speaker", on_delete=models.CASCADE)
    personFor = models.ForeignKey(Person, related_name="personFor", on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    vol_para = models.IntegerField()
    page_chapter = models.IntegerField()
    hadees_verse = models.IntegerField()
    description = models.TextField(max_length=500, null=True)
    data_status = models.CharField(max_length=3, default='-P-')
    data_user = models.CharField(max_length=10, default='Admin')

    def __str__(self):
        return str(self.subject) + ' ' + self.description

haq/views.py
from YaMehdiData.settings import AUTH_PASSWORD_VALIDATORS
from django.shortcuts import get_object_or_404, render,redirect
from django.http import HttpResponse
from .models import *
from django.contrib.auth.models import User, auth
import json, io, sys
import requests
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from serverAPI.serializers import *

################################################
# ~~~~~ General Functions ~~~~~~~~~ #
################################################
# Authorized Person ## auth_person = auth_Person_Function(str(request.user))
def auth_Person_Function(current_user_name):
    if (current_user_name.lower() == 'admin' or current_user_name.lower() == 'sam'):
        return "Authorized Person"
    return False

### Log out View

def LogOutView(request):
    auth.logout(request)
    return redirect("/")

### Delete data from JSON File
def deleteData_JSON(file_name, item_id, dictName):
    fileName = file_name
    itemID = item_id 

    jsonFile = open(f'staticfiles/{fileName}')
    data = json.load(jsonFile)
    jsonFile.close()

    for index in range(len(data['need'])):
        if data['need'][index]['id'] == str(itemID):
            data['need'].pop(index)
            break

    my_json = json.dumps(data, indent=1)

    with open(f'staticfiles/{fileName}', mode='w+') as myFile:
        myFile.write(my_json)
    myFile.close()


################################################
# ~~~~~ JSON FILES Functions & VIEWS ~~~~~~~~~ #
################################################
# create 'authorizedPersonJSON.json' file
def _createAuthPersonJSON(request):
    auth_person = Authorized_Person.objects.all()
    authPerson_list = [] # will store all auth.per in here 

    for person in auth_person:
        authPerson_list.append({
            "name": person.auth_name,
            "data_status" : person.data_status,
            "data_user" : '',
        })
        
    json_person = {"authPerson": authPerson_list}
    my_json = json.dumps(json_person, indent=1)

    with open('staticfiles/authorizedPersonJSON.json', mode='w+') as myFile:
        myFile.write(my_json)
    
    return "AuthPerson"

# create 'topicsJSON.json' file
def _createTopicsJSON():
    topics = Topic.objects.all()
    topics_list = [] # will store all topics and then go inside json_topic

    for t in topics:
        topics_list.append({
            "id": t.id, "_topic": t._topic,
            "data_status" : t.data_status,
            "data_user" : '',
        })

    # will store topics json in here
    json_data = { "topics" : topics_list }
    # convert into json data
    my_json = json.dumps(json_data, indent=1)

    with open('staticfiles/topicsJSON.json', mode='w+') as myFile:
        myFile.write(my_json)
    
    return "Topics"

# create 'categoriesJSON.json' file
def _createCategoriesJSON():
    categories = Category.objects.all()
    categories_list = [] # will store all categories and then go inside json file

    for c in categories:
        categories_list.append({
            "id": c.id,
            "_category": c._category,
            "data_status" : c.data_status,
            "data_user" : '',
        })

    # will store topics json in here
    json_data = { "categories" : categories_list }
    # convert into json data
    my_json = json.dumps(json_data, indent=1)

    with open('staticfiles/categoriesJSON.json', mode='w+') as myFile:
        myFile.write(my_json)
    
    return "Categories"


    # create 'statusJSON.json' file
def _createStatusJSON():
    status = Status.objects.all()
    status_list = [] # will store all status and then go inside json file

    for s in status:
        status_list.append({
            "id": s.id, 
            "_status": s._status,
            "data_status" : s.data_status,
            "data_user" : '',
        })

    # will store topics json in here
    json_data = { "status" : status_list }
    # convert into json data
    my_json = json.dumps(json_data, indent=1)

    with open('staticfiles/statusJSON.json', mode='w+') as myFile:
        myFile.write(my_json)
    
    return "Status"

    # create 'religionJSON.json' file
def _createReligionJSON():
    religion = Religion.objects.all()
    religion_list = [] # will store all religion and then go inside json file

    for r in religion:
        religion_list.append({
            "id": r.id, 
            "_sect": r._sect,
            "data_status" : r.data_status,
            "data_user" : '',
        })

    # will store topics json in here
    json_data = { "religion" : religion_list }
    # convert into json data
    my_json = json.dumps(json_data, indent=1)

    with open('staticfiles/religionJSON.json', mode='w+') as myFile:
        myFile.write(my_json)
    
    return "Religion"


    # create 'personJSON.json' file
def _createPersonJSON():
    person = Person.objects.all()
    person_list = [] # will store all person and then go inside json file

    for p in person:
        person_list.append({
            "id": p.id, 
            "_p_name": p._p_name,
            "_birth_year": p._birth_year, 
            "_death_year": p._death_year,
            "data_status" : p.data_status,
            "data_user" : '',
        })

    # will store topics json in here
    json_data = { "person" : person_list }
    # convert into json data
    my_json = json.dumps(json_data, indent=1)

    with open('staticfiles/personJSON.json', mode='w+') as myFile:
        myFile.write(my_json)
    
    return "Persons"

    # create 'needJSON.json' file
def _createNeedJSON():
    need = Need.objects.all()
    need_list = [] # will store all need and then go inside json file

    for n in need:
        need_list.append({
            "id": n.id, 
            "_need": n._need,
            "data_status" : n.data_status,
            "data_user" : n.data_user,
        })

    # will store need json in here
    json_data = { "need" : need_list }
    # convert into json data
    my_json = json.dumps(json_data, indent=1)

    with open('staticfiles/needJSON.json', mode='w+') as myFile:
        myFile.write(my_json)
    
    return "Need"

    # create 'languageJSON.json' file
def _createLanguageJSON():
    language = Language.objects.all()
    language_list = [] # will store all language and then go inside json file

    for l in language:
        language_list.append({
            "id": l.id, 
            "_language": l._language,
            "data_status" : l.data_status,
            "data_user" : '',
        })

    # will store language json in here
    json_data = { "language" : language_list }
    # convert into json data
    my_json = json.dumps(json_data, indent=1)

    with open('staticfiles/languageJSON.json', mode='w+') as myFile:
        myFile.write(my_json)
    
    return "Language"

    # create 'bookJSON.json' file
def _createBookJSON():
    book = Book.objects.all()
    book_list = [] # will store all book and then go inside json file

    for b in book:
        book_list.append({
            "id": b.id,
            "name": b.name, 
            "author": str(b.author),
            "sect": str(b.sect),
            "cat": str(b.cat), 
            "status": str(b.status), 
            "need": str(b.need), 
            "lang": str(b.lang),
            "data_status" : b.data_status,
            "data_user" : '',
        })
    
    # will store language json in here
    json_data = { "book" : book_list }
    
    # convert into json data
    my_json = json.dumps(json_data, indent=1)
    
    with open('staticfiles/bookJSON.json', mode='w+') as myFile:
        myFile.write(my_json)
    
    return "Book"


    # create 'referenceJSON.json' file
def _createReferenceJSON():
    reference = Reference.objects.all()
    reference_list = [] # will store all reference and then go inside json file
    
    for r in reference:
        reference_list.append({
            "id": r.id,
            "subject": str(r.subject),
            "speaker" : str(r.speaker),
            "personFor" : str(r.personFor),
            "book" : str(r.book),
            "vol_para" : r.vol_para,
            "page_chapter" : r.page_chapter,
            "hadees_verse" : r.hadees_verse,
            "description" : r.description,
            "data_status" : r.data_status,
            "data_user" : '',
        })

    # will store reference json in here
    json_data = { "reference" : reference_list }
    # convert into json data
    my_json = json.dumps(json_data, indent=2)

    with io.open('staticfiles/referenceJSON.json', mode='w+', encoding="utf-16") as myFile:
        myFile.write(my_json)
    
    return "Reference"

########################################################
def CreateJSONView(request):
    auth_person = auth_Person_Function(str(request.user))
    msg = []
    if request.method == "POST":
        create_authPerson = _createAuthPersonJSON(request)
        msg.append(create_authPerson)
        # create Topics File
        created_file = _createTopicsJSON()
        msg.append(created_file)
        # create Categories File
        created_file = _createCategoriesJSON()
        msg.append(created_file)
        # create Status File
        created_file = _createStatusJSON()
        msg.append(created_file)
        # create Religion File
        created_file = _createReligionJSON()
        msg.append(created_file)
        # create Person File
        created_file = _createPersonJSON()
        msg.append(created_file)
        # create Need File
        created_file = _createNeedJSON()
        msg.append(created_file)
        # create Language File
        created_file = _createLanguageJSON()
        msg.append(created_file)
        # create Books File
        created_file = _createBookJSON()
        msg.append(created_file)
        # create References File
        created_file = _createReferenceJSON()
        msg.append(created_file)

haq/templates/haq/sample.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <title>Universal Qaim's Page</title>
        <link href="{% static 'haq/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'haq/newStyles.css' %}" rel="stylesheet" />
        <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark" style="text-align: center;">
            <a class="navbar-brand" href="#">Yousuf-e-Zahra (a.s) </a> 
            <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
        
            <!-- Navbar-->
            <ul class="navbar-nav ml-auto ml-md-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">

                        <a class="dropdown-item" href="{% url 'haq:logout' %}">Logout</a>
                    </div>
                </li>
            </ul>
        </nav>

        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            {% if auth_person == "Authorized Person" %}
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseJSON" aria-expanded="false" aria-controls="collapseLayouts">
                                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                    JSON Files
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="collapseJSON" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <ul>
                                            <li>
                                                <a class="nav-link" href="{% url 'haq:createJSON' %}">Get All Files</a>
                                            </li>
                                            <li>
                                                <a class="nav-link" href="{% url 'haq:postJSON' %}">Post New data</a>
                                            </li>
                                            <li>
                                                <a class="nav-link" href="#">Update data</a>
                                            </li>
                                            <li>
                                                <a class="nav-link" href="#">Delete data</a>
                                            </li>
                                        </ul>
                                        
                                    </nav>
                                </div> 
                            {% endif %}
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                        Salam.. {{user.first_name}}!
                    </div>
                </nav>
            </div>

            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid">
                       
                        {% block body %}
                        {% endblock %}
                        
                    </div>
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2021 Developed By SAMMAR ABBAS</div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'haq/scripts.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="assets/demo/chart-area-demo.js"></script>
        <script src="assets/demo/chart-bar-demo.js"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
        <script src="assets/demo/datatables-demo.js"></script>
    </body>
</html>